services:
  server:
    class: com.pingidentity.opendst.it.networkfault.NetworkFaultApp$Server
    ip: 10.0.0.1
    args: ["8080"]
  client:
    class: com.pingidentity.opendst.it.networkfault.NetworkFaultApp$Client
    ip: 10.0.0.2
    args: ["10.0.0.1", "8080"]

traceAuditor:
  class: com.pingidentity.opendst.it.networkfault.NetworkFaultTraceAuditor
