services:
  alice:
    class: com.pingidentity.opendst.example.bank.AccountServer
    artifact: com.pingidentity.opendst:example-bank-transfer:war:0.0.1-SNAPSHOT
    ip: 10.0.0.1
    args: ["8001", "1000"]
  bob:
    class: com.pingidentity.opendst.example.bank.AccountServer
    artifact: com.pingidentity.opendst:example-bank-transfer:war:0.0.1-SNAPSHOT
    ip: 10.0.0.2
    args: ["8002", "1000"]
  coordinator:
    class: com.pingidentity.opendst.example.bank.Coordinator
    artifact: com.pingidentity.opendst:example-bank-transfer:war:0.0.1-SNAPSHOT
    ip: 10.0.0.3
    args: ["10.0.0.1", "8001", "10.0.0.2", "8002", "20"]
