invoker.goals.1 = clean install verify -Dopendst.parallelism=4 -DdeterminismStressorEnabled=false
invoker.buildResult.1 = failure

invoker.goals.2 = verify -Dopendst.plan=target/opendst/failures/failure-0.json
invoker.buildResult.2 = failure

