invoker.goals=clean install verify -Dopendst.parallelism=4 -DdeterminismStressorEnabled=false
invoker.buildResult = failure
# invoker.mavenOpts=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=1234

