/*
 * Copyright 2026 Ping Identity Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.pingidentity.opendst;

import static com.pingidentity.opendst.Constants.LOG_SOURCE_SIMULATOR;
import static com.pingidentity.opendst.Constants.LOG_SOURCE_VHOST;
import static java.lang.System.lineSeparator;
import static java.nio.charset.StandardCharsets.UTF_8;
import static tools.jackson.jr.ob.JSON.Feature.FLUSH_AFTER_WRITE_VALUE;

import com.pingidentity.opendst.Simulator.SimulationError;
import com.pingidentity.opendst.sdk.TraceAuditor;
import com.pingidentity.opendst.sdk.TraceAuditor.Log;
import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.time.Instant;
import java.util.ArrayList;
import tools.jackson.core.JsonGenerator;
import tools.jackson.jr.ob.JSON;

/**
 * Structured logging hub for the child JVM, serializing all simulator output as newline-delimited JSON to
 * {@code System.out} (which the parent process reads as its child's stdout).
 *
 * <p>Two independent log producers feed into this class:
 * <ul>
 *   <li><b>{@link InternalLogger}</b> — emits simulator framework signals (lifecycle, assert, guidance).
 *       Created via {@link #logLifecycle}, {@link #logAssert}, and {@link #logGuidance}. Each entry is written
 *       directly to the output stream; the {@code hashOnLog} flag controls whether the message is folded into
 *       the deterministic state hash (guidance signals are excluded).</li>
 *   <li><b>{@link LogWriter}</b> — an {@link OutputStream} assigned as each virtual host's {@code System.out}.
 *       Buffers bytes, splits on line separators, wraps each line as a JSON envelope (embedding raw JSON if the
 *       line is already a JSON object). Every line is hashed <em>and</em> buffered in {@link #unauditedLogs}
 *       for deferred {@link TraceAuditor} processing.</li>
 * </ul>
 *
 * <p>Deferred processing: {@link #processLogs()} drains the buffered {@link LogWriter} entries to
 * {@link TraceAuditor#process} and is called <em>outside</em> the simulation tick so that arbitrary user-supplied
 * auditor code cannot affect determinism.
 *
 * <p>When the system property {@code opendst.log-spy} is set, all output is additionally teed to a file via
 * {@link TeeingPrintStream} for offline debugging.
 */
final class ConsoleCapture {
    /**
     * Buffers logs generated by the workload so that they can be processed out of the simulator context to protect
     * determinism.
     */
    private final ArrayList<Log> unauditedLogs = new ArrayList<>();

    private final Simulator simulator;
    private final TraceAuditor traceAuditor;
    private final PrintStream out;
    private long logSeq;

    /** A {@link JSON} instance used for structured logging. */
    private static final JSON JSON_LOGGER =
            JSON.builder().disable(FLUSH_AFTER_WRITE_VALUE).build();

    ConsoleCapture(Simulator simulator, TraceAuditor traceAuditor, PrintStream out) throws IOException {
        this.simulator = simulator;
        this.traceAuditor = traceAuditor;
        var spyPath = System.getProperty("opendst.log-spy");
        if (spyPath != null) {
            this.out = new TeeingPrintStream(out, new FileOutputStream(spyPath, true));
        } else {
            this.out = new CloseShieldPrintStream(out);
        }
    }

    // ── Core API: log factory methods ──────────────────────────────────────────

    /**
     * Creates a lifecycle logger for simulation milestones (start, tick, stop). The message is folded into the
     * deterministic state hash on {@link InternalLogger#log()}.
     */
    InternalLogger logLifecycle(String message, Instant time, long iteration) {
        return new InternalLogger("lifecycle", message, null, time, iteration, true);
    }

    /**
     * Creates an assert logger for assertion evaluation results. The message is folded into the deterministic
     * state hash on {@link InternalLogger#log()}.
     */
    InternalLogger logAssert(String message, String vhost, Instant time, long iteration) {
        return new InternalLogger("assert", message, vhost, time, iteration, true);
    }

    /**
     * Creates a guidance logger. Guidance signals carry distance-to-violation data for
     * the orchestrator but must NOT affect the deterministic state hash — they are
     * framework-internal metadata, not application-observable behavior.
     */
    InternalLogger logGuidance(String message, String vhost, Instant time, long iteration) {
        return new InternalLogger("guidance", message, vhost, time, iteration, false);
    }

    /**
     * Creates a new {@link LogWriter} for a specific host.
     *
     * @param host The host associated with the logs.
     * @return A new {@link LogWriter} instance.
     */
    public LogWriter newLogWriter(String host) {
        return new LogWriter(host);
    }

    // ── Lifecycle ──────────────────────────────────────────────────────────────

    /**
     * Drains all buffered {@link LogWriter} entries to {@link TraceAuditor#process}. Called <em>outside</em> the
     * simulation tick so that arbitrary user-supplied auditor code cannot interfere with deterministic execution.
     */
    void processLogs() throws Throwable {
        for (var log : unauditedLogs) {
            traceAuditor.process(log);
        }
        unauditedLogs.clear();
    }

    /** Flushes the underlying output stream to ensure all JSON log entries are delivered to the parent process. */
    void flush() {
        out.flush();
    }

    /**
     * Returns the output stream that all JSON log entries are written to. This is the child process's
     * {@code System.out} (optionally wrapped in a {@link TeeingPrintStream} for spy-file debugging),
     * which the parent process reads as structured newline-delimited JSON.
     */
    PrintStream getOut() {
        return out;
    }

    // ── Inner classes: log producers ───────────────────────────────────────────

    /**
     * Builder that writes a single structured JSON log entry for a simulator framework signal (lifecycle, assert,
     * or guidance). The JSON object is opened in the constructor and committed when {@link #log()} is called.
     *
     * <p>The {@code hashOnLog} flag controls whether the message is folded into the deterministic state hash
     * on {@link #log()} — guidance signals set this to {@code false} because they carry framework-internal
     * metadata that must not affect reproducibility.
     */
    final class InternalLogger {
        private final JsonGenerator generator;
        private final String message;
        private final boolean hashOnLog;

        InternalLogger(String type, String message, String vhost, Instant time, long iteration, boolean hashOnLog) {
            this.message = message;
            this.hashOnLog = hashOnLog;
            // NOTE: vhost might be null for some low-level simulator's message.
            var gen = JSON_LOGGER
                    .createGenerator(out)
                    .writeStartObject()
                    .writeNumberProperty("lid", logSeq++)
                    .writeStringProperty("source", LOG_SOURCE_SIMULATOR);
            if (vhost != null) {
                gen.writeStringProperty("vhost", vhost);
            }
            this.generator = gen.writeNumberProperty("it", iteration)
                    .writeName("log")
                    .writeStartObject()
                    .writeStringProperty("type", type)
                    .writeStringProperty("message", message)
                    .writeStringProperty("at", time.toString());
        }

        InternalLogger withPOJO(String name, Object value) {
            if (value != null) {
                generator.writePOJOProperty(name, value);
            }
            return this;
        }

        InternalLogger withString(String name, String value) {
            if (value != null) {
                this.generator.writeStringProperty(name, value);
            }
            return this;
        }

        InternalLogger withNumber(String name, long value) {
            this.generator.writeNumberProperty(name, value);
            return this;
        }

        InternalLogger withBoolean(String name, boolean value) {
            this.generator.writeBooleanProperty(name, value);
            return this;
        }

        void log() {
            generator.writeEndObject().writeEndObject().close();
            out.write('\n');
            if (hashOnLog) {
                simulator.hash(message);
            }
        }
    }

    /**
     * An {@link OutputStream} assigned as a virtual host's {@code System.out}. Buffers bytes, splits on line
     * separators, and wraps each complete line as a JSON envelope written to the parent-facing output stream.
     *
     * <p>If a line is already a JSON object ({@code \{...\}}), it is embedded as a raw value; otherwise it is
     * wrapped in a {@code type:stdout} object. Every line is hashed into the deterministic state and buffered
     * in {@link #unauditedLogs} for deferred {@link TraceAuditor} processing via {@link #processLogs()}.
     */
    final class LogWriter extends OutputStream {
        private final String host;
        private final ByteArrayOutputStream consoleOut = new ByteArrayOutputStream();

        LogWriter(String host) {
            this.host = host;
        }

        @Override
        public void write(int b) {
            consoleOut.write(b);
        }

        @Override
        public void write(byte[] b, int off, int len) {
            consoleOut.write(b, off, len);
        }

        @Override
        public void flush() {
            if (consoleOut.size() > 0) {
                var str = consoleOut.toString(UTF_8);
                int end = str.indexOf(lineSeparator());
                int start = 0;
                while (end != -1) {
                    log(str.substring(start, end));
                    start = end + lineSeparator().length();
                    end = str.indexOf(lineSeparator(), start);
                }

                try {
                    consoleOut.reset();
                    if (start < str.length()) {
                        consoleOut.write(str.substring(start).getBytes(UTF_8));
                    }
                } catch (IOException e) {
                    // Should never happen
                    throw new SimulationError(e);
                }
            }
        }

        private void log(String message) {
            try (var gen = JSON_LOGGER.createGenerator(out)) {
                gen.writeStartObject()
                        .writeNumberProperty("lid", logSeq++)
                        .writeStringProperty("source", LOG_SOURCE_VHOST)
                        .writeStringProperty("vhost", host)
                        .writeNumberProperty("it", simulator.iteration());
                if (message != null && message.startsWith("{") && message.endsWith("}")) {
                    gen.writeName("log");
                    gen.writeRawValue(message);
                } else {
                    gen.writeName("log")
                            .writeStartObject()
                            .writeStringProperty("type", "stdout")
                            .writeStringProperty("message", message)
                            .writeStringProperty("at", simulator.instant().toString())
                            .writeEndObject();
                }
                gen.writeEndObject();
            }
            out.write('\n');
            simulator.hash(message);
            unauditedLogs.add(new Log(host, simulator.instant(), simulator.iteration(), message));
        }
    }

    // ── Plumbing: stream wrappers ──────────────────────────────────────────────

    /**
     * A {@link PrintStream} that writes to a primary stream and tees all output to a secondary {@link OutputStream}.
     * Close-shields the primary: only the secondary is closed on {@link #close()}.
     */
    private static final class TeeingPrintStream extends PrintStream {
        private final OutputStream secondary;

        TeeingPrintStream(PrintStream primary, OutputStream secondary) {
            super(primary, true, UTF_8);
            this.secondary = secondary;
        }

        @Override
        public void write(int b) {
            super.write(b);
            try {
                secondary.write(b);
            } catch (IOException e) {
                setError();
            }
        }

        @Override
        public void write(byte[] b, int off, int len) {
            super.write(b, off, len);
            try {
                secondary.write(b, off, len);
            } catch (IOException e) {
                setError();
            }
        }

        @Override
        public void flush() {
            super.flush();
            try {
                secondary.flush();
            } catch (IOException e) {
                setError();
            }
        }

        @Override
        public void close() {
            // Do not close the primary (close-shield), only close the secondary.
            try {
                secondary.close();
            } catch (IOException e) {
                setError();
            }
        }
    }

    private static final class CloseShieldPrintStream extends PrintStream {
        CloseShieldPrintStream(PrintStream delegate) {
            super(delegate);
        }

        @Override
        public void close() {
            // Do *not* close
        }
    }
}
