/*
 * Copyright 2026 Ping Identity Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.pingidentity.opendst;

import static com.pingidentity.opendst.Constants.LOG_SOURCE_SIMULATOR;
import static com.pingidentity.opendst.Constants.LOG_SOURCE_VHOST;
import static java.lang.System.lineSeparator;
import static java.nio.charset.StandardCharsets.UTF_8;
import static java.nio.file.Files.createDirectories;
import static tools.jackson.jr.ob.JSON.Feature.FLUSH_AFTER_WRITE_VALUE;

import com.pingidentity.opendst.Simulator.SimulationError;
import com.pingidentity.opendst.api.TraceAuditor;
import com.pingidentity.opendst.api.TraceAuditor.Log;
import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import tools.jackson.core.JsonGenerator;
import tools.jackson.jr.ob.JSON;

/**
 * Provides logging capabilities for the simulator.
 * Captures messages sent to console by simulated nodes, translates these to structured JSON logs and forwards these to
 * the real console
 */
final class ConsoleCapture {
    /**
     * Buffers logs generated by the workload so that they can be processed out of the simulator context to protect
     * determinism.
     */
    private final ArrayList<Log> unprocessedLogs = new ArrayList<>();

    private final Simulator simulator;
    private final TraceAuditor traceAuditor;
    private final PrintStream out;
    private long logSeq;

    /**
     * A {@link JSON} instance used for structured logging.
     */
    private static final JSON JSON_LOGGER =
            JSON.builder().disable(FLUSH_AFTER_WRITE_VALUE).build();

    ConsoleCapture(Simulator simulator, TraceAuditor traceAuditor, PrintStream out) {
        this.simulator = simulator;
        this.traceAuditor = traceAuditor;
        var spyPath = System.getProperty("opendst.log-spy");
        if (spyPath != null) {
            try {
                // Ensure directory exists
                var path = Path.of(spyPath);
                if (path.getParent() != null) {
                    createDirectories(path.getParent());
                }
                this.out = new CloseShieldPrintStream(new PrintStream(
                        new MultiOutputStream(out, new PrintStream(new FileOutputStream(spyPath, true), true, UTF_8))));
            } catch (IOException e) {
                throw new SimulationError("Failed to open log spy file: %s".formatted(spyPath), e);
            }
        } else {
            this.out = new CloseShieldPrintStream(out);
        }
    }

    PrintStream getOut() {
        return out;
    }

    private static final class MultiOutputStream extends OutputStream {
        private final OutputStream out1;
        private final OutputStream out2;

        MultiOutputStream(OutputStream out1, OutputStream out2) {
            this.out1 = out1;
            this.out2 = out2;
        }

        @Override
        public void write(int b) throws IOException {
            out1.write(b);
            out2.write(b);
        }

        @Override
        public void write(byte[] b, int off, int len) throws IOException {
            out1.write(b, off, len);
            out2.write(b, off, len);
        }

        @Override
        public void flush() throws IOException {
            out1.flush();
            out2.flush();
        }

        @Override
        public void close() throws IOException {
            try {
                out1.close();
            } finally {
                out2.close();
            }
        }
    }

    public InternalLogger logLifecycle(String message, Instant time, long iteration) {
        return new InternalLogger("lifecycle", message, null, time, iteration);
    }

    public InternalLogger logAssert(String message, String vhost, Instant time, long iteration) {
        return new InternalLogger("assert", message, vhost, time, iteration);
    }

    public InternalLogger logFault(String message, Instant time, long iteration) {
        return new InternalLogger("fault", message, null, time, iteration);
    }

    public final class InternalLogger {
        private final JsonGenerator generator;
        private final String message;

        public InternalLogger(String type, String message, String vhost, Instant time, long iteration) {
            this.message = message;
            // NOTE: vhost might be null for some low-level simulator's message.
            var gen = JSON_LOGGER
                    .createGenerator(out)
                    .writeStartObject()
                    .writeNumberProperty("lid", logSeq++)
                    .writeStringProperty("source", LOG_SOURCE_SIMULATOR);
            if (vhost != null) {
                gen.writeStringProperty("vhost", vhost);
            }
            this.generator = gen.writeNumberProperty("it", iteration)
                    .writeName("log")
                    .writeStartObject()
                    .writeStringProperty("type", type)
                    .writeStringProperty("message", message)
                    .writeStringProperty("at", time.toString());
        }

        public InternalLogger withPOJO(String name, Object value) {
            if (value != null) {
                generator.writePOJOProperty(name, value);
            }
            return this;
        }

        public InternalLogger withString(String name, String value) {
            if (value != null) {
                this.generator.writeStringProperty(name, value);
            }
            return this;
        }

        public InternalLogger withNumber(String name, long value) {
            this.generator.writeNumberProperty(name, value);
            return this;
        }

        public InternalLogger withBoolean(String name, boolean value) {
            this.generator.writeBooleanProperty(name, value);
            return this;
        }

        public void log() {
            generator.writeEndObject().writeEndObject().close();
            out.write('\n');
            simulator.hash(message);
        }
    }

    /**
     * Creates a new {@link LogWriter} for a specific host.
     *
     * @param host The host associated with the logs.
     * @return A new {@link LogWriter} instance.
     */
    public LogWriter newLogWriter(String host) {
        return new LogWriter(host);
    }

    /**
     * An {@link OutputStream} that captures log messages and formats them as JSON before sending them to the
     * VictoriaLog instance.
     */
    final class LogWriter extends OutputStream {
        private final String host;
        private final ByteArrayOutputStream consoleOut = new ByteArrayOutputStream();

        LogWriter(String host) {
            this.host = host;
        }

        @Override
        public void write(int b) {
            consoleOut.write(b);
        }

        @Override
        public void write(byte[] b, int off, int len) {
            consoleOut.write(b, off, len);
        }

        @Override
        public void flush() {
            if (consoleOut.size() > 0) {
                var str = consoleOut.toString(UTF_8);
                int end = str.indexOf(lineSeparator());
                int start = 0;
                while (end != -1) {
                    log(str.substring(start, end));
                    start = end + lineSeparator().length();
                    end = str.indexOf(lineSeparator(), start);
                }

                try {
                    consoleOut.reset();
                    if (start < str.length()) {
                        consoleOut.write(str.substring(start).getBytes(UTF_8));
                    }
                } catch (IOException e) {
                    // Should never happen
                    throw new SimulationError(e);
                }
            }
        }

        private void log(String message) {
            try (var gen = JSON_LOGGER.createGenerator(out)) {
                gen.writeStartObject()
                        .writeNumberProperty("lid", logSeq++)
                        .writeStringProperty("source", LOG_SOURCE_VHOST)
                        .writeStringProperty("vhost", host)
                        .writeNumberProperty("it", simulator.iteration());
                if (message != null && message.startsWith("{") && message.endsWith("}")) {
                    gen.writeName("log");
                    gen.writeRawValue(message);
                } else {
                    gen.writeName("log")
                            .writeStartObject()
                            .writeStringProperty("type", "stdout")
                            .writeStringProperty("message", message)
                            .writeStringProperty("at", simulator.instant().toString())
                            .writeEndObject();
                }
                gen.writeEndObject();
            }
            out.write('\n');
            simulator.hash(message);
            unprocessedLogs.add(new Log(host, simulator.instant(), simulator.iteration(), message));
        }
    }

    void processLogs() throws Throwable {
        for (var unprocessedLog : unprocessedLogs) {
            traceAuditor.process(unprocessedLog);
        }
        unprocessedLogs.clear();
    }

    void flush() {
        out.flush();
    }

    private static final class CloseShieldPrintStream extends PrintStream {
        CloseShieldPrintStream(PrintStream delegate) {
            super(delegate);
        }

        @Override
        public void close() {
            // Do *not* close
        }
    }
}
