/*
 * Copyright 2026 Ping Identity Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.pingidentity.opendst.simulator;

import static com.pingidentity.opendst.common.Constants.LOG_SOURCE_SIMULATOR;
import static com.pingidentity.opendst.common.Constants.LOG_SOURCE_VHOST;
import static java.lang.System.lineSeparator;
import static java.nio.charset.StandardCharsets.UTF_8;
import static tools.jackson.jr.ob.JSON.Feature.FLUSH_AFTER_WRITE_VALUE;
import static tools.jackson.jr.ob.JSON.Feature.WRITE_NULL_PROPERTIES;

import com.pingidentity.opendst.common.AssertType;
import com.pingidentity.opendst.common.Signal;
import com.pingidentity.opendst.common.Signal.AssertSignal;
import com.pingidentity.opendst.common.Signal.ConsoleSignal;
import com.pingidentity.opendst.common.Signal.GuidanceSignal;
import com.pingidentity.opendst.common.Signal.InternalErrorSignal;
import com.pingidentity.opendst.common.Signal.NonDeterminismSignal;
import com.pingidentity.opendst.common.Signal.PlatformThreadShutdownHookSkippedSignal;
import com.pingidentity.opendst.common.Signal.PlatformThreadStartedSignal;
import com.pingidentity.opendst.common.Signal.SegmentCompletedSignal;
import com.pingidentity.opendst.common.Signal.StartedSignal;
import com.pingidentity.opendst.common.Signal.StoppedSignal;
import com.pingidentity.opendst.common.Signal.TraceAuditorExceptionSignal;
import com.pingidentity.opendst.common.Signal.UncaughtExceptionSignal;
import com.pingidentity.opendst.common.SimulationEvent;
import com.pingidentity.opendst.sdk.TraceAuditor;
import com.pingidentity.opendst.sdk.TraceAuditor.Log;
import com.pingidentity.opendst.simulator.Simulator.SimulationError;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import tools.jackson.core.JsonGenerator;
import tools.jackson.jr.ob.JSON;
import tools.jackson.jr.ob.JacksonJrExtension;
import tools.jackson.jr.ob.api.ExtensionContext;
import tools.jackson.jr.ob.api.ReaderWriterProvider;
import tools.jackson.jr.ob.api.ValueWriter;
import tools.jackson.jr.ob.impl.JSONWriter;

/**
 * Structured logging hub for the child JVM, serializing all simulator output as newline-delimited JSON to
 * {@code System.out} (which the parent process reads as its child's stdout).
 *
 * <p>The class exposes one method per {@link Signal} subtype (e.g. {@link #logStarted}, {@link #logStopped},
 * {@link #logAssert}). Each constructs the typed signal record and routes it through {@link #emit}, which
 * writes a JSON envelope around the signal payload.
 *
 * <p>The wire format of each line is:
 * <pre>{ "lid", "source", "vhost"?, "it", "at", "signal": &lt;signal&gt; }</pre>
 *
 * <p>Two stream-side producers contribute to the output:
 * <ul>
 *   <li>The framework methods named above (lifecycle / assert / guidance / fault).</li>
 *   <li>{@link LogWriter} — an {@link OutputStream} assigned as each virtual host's {@code System.out}.
 *       Buffers bytes, splits on line separators, and emits each complete line as a {@link ConsoleSignal}
 *       (or embeds it raw if the line is already a JSON object). Every line is hashed and buffered in
 *       {@link #unauditedLogs} for deferred {@link TraceAuditor} processing.</li>
 * </ul>
 *
 * <p>Deferred processing: {@link #flush()} drains the buffered {@link LogWriter} entries to
 * {@link TraceAuditor#process} and is called <em>outside</em> the simulation tick so that arbitrary
 * user-supplied auditor code cannot affect determinism.
 */
public final class ConsoleCapture {

    /**
     * A {@link JSON} instance used for structured logging. Configured with custom value writers for
     * {@link Signal} (polymorphic dispatch on the runtime subtype, emitting the {@code type}
     * discriminator and subtype-specific fields) and {@link Instant} (ISO-8601 string). Null record
     * components are omitted so that the {@code vhost} field is absent for simulator-framework
     * signals.
     */
    private static final JSON JSON_LOGGER = JSON.builder()
            .disable(FLUSH_AFTER_WRITE_VALUE)
            .disable(WRITE_NULL_PROPERTIES)
            .register(new SignalCodec())
            .build();

    /**
     * Buffers logs generated by the workload so that they can be processed out of the simulator context to protect
     * determinism.
     */
    private final ArrayList<Log> unauditedLogs = new ArrayList<>();

    private final Simulator simulator;
    private final TraceAuditor traceAuditor;
    private final PrintStream out;
    private long logSeq;
    private boolean traceAuditorFailed;

    ConsoleCapture(Simulator simulator, TraceAuditor traceAuditor, PrintStream out) throws IOException {
        this.simulator = simulator;
        this.traceAuditor = traceAuditor;
        this.out = new CloseShieldPrintStream(out);
    }

    // ── Framework signals: one method per Signal subtype ──────────────────────

    /** Emits a {@code started} lifecycle signal. */
    void logStarted(Instant time) {
        emit(new StartedSignal(), null, time, 0, true);
    }

    /** Emits a {@code segment-completed} lifecycle signal carrying the deterministic hash. */
    void logSegmentCompleted(int hash, Instant time, long iteration) {
        emit(new SegmentCompletedSignal(hash), null, time, iteration, true);
    }

    /** Emits a {@code stopped} lifecycle signal carrying the final deterministic hash. */
    void logStopped(int hash, Instant time, long iteration) {
        emit(new StoppedSignal(hash), null, time, iteration, true);
    }

    /** Emits a {@code non-determinism} lifecycle signal with the expected/actual hashes. */
    void logNonDeterminism(int expectedHash, int actualHash, Instant time, long iteration) {
        emit(new NonDeterminismSignal(expectedHash, actualHash), null, time, iteration, true);
    }

    /** Emits an {@code internal-error} lifecycle signal with cause + stacktrace. */
    void logInternalError(String cause, List<String> stacktrace, Instant time, long iteration) {
        emit(new InternalErrorSignal(cause, stacktrace), null, time, iteration, true);
    }

    /** Emits a {@code trace-auditor-exception} lifecycle signal with cause + stacktrace. */
    void logTraceAuditorException(String cause, List<String> stacktrace, Instant time, long iteration) {
        emit(new TraceAuditorExceptionSignal(cause, stacktrace), null, time, iteration, true);
    }

    /** Emits an {@code uncaught-exception} lifecycle signal for a virtual-host thread. */
    void logUncaughtException(String vhost, String thread, Throwable exception, Instant time, long iteration) {
        emit(new UncaughtExceptionSignal(vhost, thread, exception), vhost, time, iteration, true);
    }

    /** Emits a diagnostic signal: a platform (non-virtual) thread started inside a virtual host. */
    public void logPlatformThreadStarted(
            String vhost, String threadName, String threadClass, String caller, Instant time, long iteration) {
        emit(new PlatformThreadStartedSignal(vhost, threadName, threadClass, caller), vhost, time, iteration, true);
    }

    /** Emits a diagnostic signal: a JVM shutdown hook was registered by a virtual host and skipped. */
    void logPlatformThreadShutdownHookSkipped(
            String vhost, String hookClass, String hookName, Instant time, long iteration) {
        emit(new PlatformThreadShutdownHookSkippedSignal(vhost, hookClass, hookName), vhost, time, iteration, true);
    }

    /**
     * Emits an {@link AssertSignal} for an assertion evaluation. The message is folded into the
     * deterministic state hash.
     */
    void logAssert(
            AssertType kind,
            String message,
            boolean condition,
            Map<String, Object> details,
            String vhost,
            Instant time,
            long iteration) {
        emit(new AssertSignal(kind, message, condition, details), vhost, time, iteration, true);
    }

    /**
     * Emits a {@link GuidanceSignal} carrying distance-to-violation data for the runner.
     * Guidance signals do <em>not</em> affect the deterministic state hash.
     */
    void logGuidance(String message, Map<String, Object> guidance, String vhost, Instant time, long iteration) {
        emit(new GuidanceSignal(message, guidance), vhost, time, iteration, false);
    }

    /**
     * Creates a new {@link LogWriter} for a specific host.
     *
     * @param host The host associated with the logs.
     * @return A new {@link LogWriter} instance.
     */
    LogWriter newLogWriter(String host) {
        return new LogWriter(host);
    }

    // ── Lifecycle ──────────────────────────────────────────────────────────────

    /**
     * Flushes the underlying output stream to ensure all JSON log entries are delivered to the parent process.
     * Drains all buffered {@link LogWriter} entries to {@link TraceAuditor#process}. Called <em>outside</em> the
     * simulation tick so that arbitrary user-supplied auditor code cannot interfere with deterministic execution.
     */
    void flush() {
        out.flush();
        try {
            for (var log : unauditedLogs) {
                traceAuditor.process(log);
            }
            unauditedLogs.clear();
        } catch (Throwable e) {
            if (!traceAuditorFailed) {
                traceAuditorFailed = true;
                logTraceAuditorException(
                        e.getMessage(),
                        java.util.Arrays.stream(e.getStackTrace())
                                .limit(10)
                                .map(StackTraceElement::toString)
                                .toList(),
                        simulator.instant(),
                        simulator.iteration());
            }
        }
    }

    /**
     * Returns the output stream that all JSON log entries are written to. This is the child process's
     * {@code System.out}, which the parent process reads as structured newline-delimited JSON.
     */
    PrintStream getOut() {
        return out;
    }

    // ── Centralized emission ──────────────────────────────────────────────────

    /**
     * Writes one structured JSON line: the {@link SimulationEvent} envelope wrapping the typed
     * {@link Signal} payload. Field-level serialization is delegated to {@link SignalCodec}.
     *
     * @param signal    the typed signal to emit
     * @param vhost     the virtual host the signal pertains to, or {@code null} for simulator-framework signals
     * @param time      the simulator instant at which the signal was emitted
     * @param iteration the simulator iteration counter
     * @param hashOnLog whether to fold {@code signal.message()} into the deterministic state hash (false for
     *                  guidance signals; they carry framework-internal metadata that must not affect reproducibility)
     */
    private void emit(Signal signal, String vhost, Instant time, long iteration, boolean hashOnLog) {
        var source = vhost != null ? LOG_SOURCE_VHOST : LOG_SOURCE_SIMULATOR;
        JSON_LOGGER.write(new SimulationEvent(logSeq++, source, vhost, iteration, time, signal), out);
        out.write('\n');
        if (hashOnLog) {
            simulator.hash(signal.message());
        }
    }

    /**
     * Custom {@code jackson-jr} extension that registers value writers for {@link Signal} (polymorphic
     * dispatch on subtype, emitting {@code type}/{@code message}/subtype fields) and {@link Instant}
     * (ISO-8601 string). The {@link Signal} writer is selected via {@code Signal.class.isAssignableFrom}
     * so that all 14 sealed subtypes are dispatched to the same writer.
     */
    private static final class SignalCodec extends JacksonJrExtension {
        @Override
        protected void register(ExtensionContext ctxt) {
            ctxt.appendProvider(new ReaderWriterProvider() {
                @Override
                public ValueWriter findValueWriter(JSONWriter writeContext, Class<?> type) {
                    if (Signal.class.isAssignableFrom(type)) {
                        return SIGNAL_WRITER;
                    } else if (Instant.class.isAssignableFrom(type)) {
                        return INSTANT_WRITER;
                    }
                    return null;
                }
            });
        }
    }

    private static final ValueWriter INSTANT_WRITER = new ValueWriter() {
        @Override
        public void writeValue(JSONWriter context, JsonGenerator g, Object value) {
            g.writeString(value.toString());
        }

        @Override
        public Class<?> valueType() {
            return Instant.class;
        }
    };

    private static final ValueWriter SIGNAL_WRITER = new ValueWriter() {
        @Override
        public void writeValue(JSONWriter context, JsonGenerator g, Object value) {
            var signal = (Signal) value;
            g.writeStartObject();
            g.writeStringProperty("type", signal.type());
            g.writeStringProperty("message", signal.message());
            writeSubtypeFields(g, signal);
            g.writeEndObject();
        }

        @Override
        public Class<?> valueType() {
            return Signal.class;
        }
    };

    /** Writes the subtype-specific fields of {@code signal} into the currently-open inner JSON object. */
    private static void writeSubtypeFields(JsonGenerator gen, Signal signal) {
        switch (signal) {
            case ConsoleSignal ignored -> {
                /* message already written */
            }
            case StartedSignal ignored -> {
                /* no extra fields */
            }
            case SegmentCompletedSignal s -> gen.writeNumberProperty("hash", s.hash());
            case StoppedSignal s -> gen.writeNumberProperty("hash", s.hash());
            case NonDeterminismSignal s ->
                gen.writeNumberProperty("expectedHash", s.expectedHash())
                        .writeNumberProperty("actualHash", s.actualHash());
            case InternalErrorSignal s -> writeCauseAndStacktrace(gen, s.cause(), s.stacktrace());
            case TraceAuditorExceptionSignal s -> writeCauseAndStacktrace(gen, s.cause(), s.stacktrace());
            case UncaughtExceptionSignal s -> {
                if (s.vhost() != null) {
                    gen.writeStringProperty("vhost", s.vhost());
                }
                if (s.thread() != null) {
                    gen.writeStringProperty("thread", s.thread());
                }
                if (s.exception() != null) {
                    gen.writePOJOProperty("exception", s.exception());
                }
            }
            case PlatformThreadStartedSignal s -> {
                if (s.vhost() != null) {
                    gen.writeStringProperty("vhost", s.vhost());
                }
                gen.writeStringProperty("threadName", s.threadName())
                        .writeStringProperty("threadClass", s.threadClass())
                        .writeStringProperty("caller", s.caller());
            }
            case PlatformThreadShutdownHookSkippedSignal s -> {
                if (s.vhost() != null) {
                    gen.writeStringProperty("vhost", s.vhost());
                }
                gen.writeStringProperty("hookClass", s.hookClass()).writeStringProperty("hookName", s.hookName());
            }
            case AssertSignal s -> {
                gen.writeStringProperty("kind", s.kind().toString()).writeBooleanProperty("condition", s.condition());
                if (s.details() != null) {
                    gen.writePOJOProperty("details", s.details());
                }
            }
            case GuidanceSignal s -> {
                if (s.guidance() != null) {
                    gen.writePOJOProperty("guidance", s.guidance());
                }
            }
            case Signal.FaultSignal ignored -> {
                /* message already written */
            }
        }
    }

    private static void writeCauseAndStacktrace(JsonGenerator gen, String cause, List<String> stacktrace) {
        if (cause != null) {
            gen.writeStringProperty("cause", cause);
        }
        if (stacktrace != null) {
            gen.writePOJOProperty("stacktrace", stacktrace);
        }
    }

    // ── Inner classes ─────────────────────────────────────────────────────────

    /**
     * An {@link OutputStream} assigned as a virtual host's {@code System.out}. Buffers bytes, splits on line
     * separators, and emits each complete line as a {@link ConsoleSignal} (embedding raw JSON if the line is
     * already a JSON object). Every line is hashed into the deterministic state and buffered in
     * {@link #unauditedLogs} for deferred {@link TraceAuditor} processing via {@link #flush()}.
     */
    final class LogWriter extends OutputStream {
        private final String host;
        private final ByteArrayOutputStream consoleOut = new ByteArrayOutputStream();

        LogWriter(String host) {
            this.host = host;
        }

        @Override
        public void write(int b) {
            consoleOut.write(b);
        }

        @Override
        public void write(byte[] b, int off, int len) {
            consoleOut.write(b, off, len);
        }

        @Override
        public void flush() {
            if (consoleOut.size() > 0) {
                var str = consoleOut.toString(UTF_8);
                int end = str.indexOf(lineSeparator());
                int start = 0;
                while (end != -1) {
                    log(str.substring(start, end));
                    start = end + lineSeparator().length();
                    end = str.indexOf(lineSeparator(), start);
                }

                try {
                    consoleOut.reset();
                    if (start < str.length()) {
                        consoleOut.write(str.substring(start).getBytes(UTF_8));
                    }
                } catch (IOException e) {
                    // Should never happen
                    throw new SimulationError(e);
                }
            }
        }

        private void log(String message) {
            // Lines that are already structured JSON are embedded raw inside the envelope, bypassing the
            // ConsoleSignal type — useful for nested signals from agents that already speak the protocol.
            // This is a hand-written carve-out: the polymorphic Signal writer registered in JSON_LOGGER
            // cannot embed a raw JSON string, so we write the SimulationEvent envelope manually here.
            if (message != null && message.startsWith("{") && message.endsWith("}")) {
                try (var gen = JSON_LOGGER.createGenerator(out)) {
                    gen.writeStartObject()
                            .writeNumberProperty("lid", logSeq++)
                            .writeStringProperty("source", LOG_SOURCE_VHOST)
                            .writeStringProperty("vhost", host)
                            .writeNumberProperty("it", simulator.iteration())
                            .writeStringProperty("at", simulator.instant().toString())
                            .writeName("signal");
                    gen.writeRawValue(message);
                    gen.writeEndObject();
                }
                out.write('\n');
            } else {
                emit(new ConsoleSignal(message), host, simulator.instant(), simulator.iteration(), false);
            }
            simulator.hash(message);
            unauditedLogs.add(new Log(host, simulator.instant(), simulator.iteration(), message));
        }
    }

    /**
     * A {@link PrintStream} that close-shields its delegate. Used so that the agent never closes
     * the child JVM's real {@code System.out} (which would prevent any further structured output).
     */
    private static final class CloseShieldPrintStream extends PrintStream {
        CloseShieldPrintStream(PrintStream delegate) {
            super(delegate);
        }

        @Override
        public void close() {
            // Do *not* close
        }
    }
}
