/*
 * Copyright 2026 Ping Identity Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.pingidentity.opendst.simulator;

import static com.pingidentity.opendst.common.Constants.LOG_SOURCE_SIMULATOR;
import static com.pingidentity.opendst.common.Constants.LOG_SOURCE_VHOST;
import static java.lang.System.lineSeparator;
import static java.nio.charset.StandardCharsets.UTF_8;
import static tools.jackson.jr.ob.JSON.Feature.FLUSH_AFTER_WRITE_VALUE;
import static tools.jackson.jr.ob.JSON.Feature.WRITE_NULL_PROPERTIES;

import com.pingidentity.opendst.common.Signal;
import com.pingidentity.opendst.common.Signal.ConsoleSignal;
import com.pingidentity.opendst.common.Signal.TraceAuditorExceptionSignal;
import com.pingidentity.opendst.common.SimulationEvent;
import com.pingidentity.opendst.sdk.TraceAuditor;
import com.pingidentity.opendst.sdk.TraceAuditor.Log;
import com.pingidentity.opendst.simulator.Simulator.SimulationError;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Set;
import tools.jackson.core.JsonGenerator;
import tools.jackson.jr.ob.JSON;
import tools.jackson.jr.ob.JacksonJrExtension;
import tools.jackson.jr.ob.api.ExtensionContext;
import tools.jackson.jr.ob.api.ReaderWriterProvider;
import tools.jackson.jr.ob.api.ValueWriter;
import tools.jackson.jr.ob.impl.JSONWriter;

/**
 * Structured logging hub for the child JVM, serializing all simulator output as newline-delimited JSON to
 * {@code System.out} (which the parent process reads as its child's stdout).
 *
 * <p>External callers reach this class via {@link Node#log(Signal)} (per-node signals) and
 * {@link Simulator#log(Signal)} (simulation-global signals), both of which delegate to {@link #emit}.
 * Each line is a JSON envelope:
 * <pre>{ "lid", "source", "vhost"?, "it", "at", "signal": &lt;signal&gt; }</pre>
 *
 * <p>{@link LogWriter} is an additional producer: assigned as each virtual host's {@code System.out}, it
 * buffers bytes, splits on line separators, and emits each complete line as a {@link ConsoleSignal} (or
 * embeds it raw if the line is already a JSON object). Every line is hashed and buffered in
 * {@link #unauditedLogs} for deferred {@link TraceAuditor} processing via {@link #flush()}, which runs
 * outside the simulation tick so user-supplied auditor code cannot affect determinism.
 */
public final class ConsoleCapture {

    /**
     * A {@link JSON} instance used for structured logging. Configured with custom value writers for
     * {@link Signal} (polymorphic dispatch on the runtime subtype, emitting the {@code type}
     * discriminator and subtype-specific fields) and {@link Instant} (ISO-8601 string). Null record
     * components are omitted so that the {@code vhost} field is absent for simulator-framework
     * signals.
     */
    private static final JSON JSON_LOGGER = JSON.builder()
            .disable(FLUSH_AFTER_WRITE_VALUE)
            .disable(WRITE_NULL_PROPERTIES)
            .register(new SignalCodec())
            .build();

    /**
     * Buffers logs generated by the workload so that they can be processed out of the simulator context to protect
     * determinism.
     */
    private final ArrayList<Log> unauditedLogs = new ArrayList<>();

    private final Simulator simulator;
    private final TraceAuditor traceAuditor;
    private final PrintStream out;
    private long logSeq;
    private boolean traceAuditorFailed;

    ConsoleCapture(Simulator simulator, TraceAuditor traceAuditor, PrintStream out) throws IOException {
        this.simulator = simulator;
        this.traceAuditor = traceAuditor;
        this.out = new CloseShieldPrintStream(out);
    }

    /**
     * Creates a new {@link LogWriter} for a specific node.
     *
     * @param node The node whose console output this writer captures.
     * @return A new {@link LogWriter} instance.
     */
    LogWriter newLogWriter(Node node) {
        return new LogWriter(node);
    }

    // ── Lifecycle ──────────────────────────────────────────────────────────────

    /**
     * Flushes the underlying output stream to ensure all JSON log entries are delivered to the parent process.
     * Drains all buffered {@link LogWriter} entries to {@link TraceAuditor#process}. Called <em>outside</em> the
     * simulation tick so that arbitrary user-supplied auditor code cannot interfere with deterministic execution.
     */
    void flush() {
        out.flush();
        try {
            for (var log : unauditedLogs) {
                traceAuditor.process(log);
            }
            unauditedLogs.clear();
        } catch (Throwable e) {
            if (!traceAuditorFailed) {
                traceAuditorFailed = true;
                simulator.log(new TraceAuditorExceptionSignal(
                        e.getMessage(),
                        java.util.Arrays.stream(e.getStackTrace())
                                .limit(10)
                                .map(StackTraceElement::toString)
                                .toList()));
            }
        }
    }

    /**
     * Returns the output stream that all JSON log entries are written to. This is the child process's
     * {@code System.out}, which the parent process reads as structured newline-delimited JSON.
     */
    PrintStream getOut() {
        return out;
    }

    // ── Centralized emission ──────────────────────────────────────────────────

    /**
     * Writes one structured JSON line: the {@link SimulationEvent} envelope wrapping the typed
     * {@link Signal} payload. Field-level serialization is delegated to {@link SignalCodec}.
     * Always folds {@code signal.message()} into the deterministic state hash.
     *
     * @param signal    the typed signal to emit
     * @param vhost     the virtual host the signal pertains to, or {@code null} for simulator-framework signals
     * @param time      the simulator instant at which the signal was emitted
     * @param iteration the simulator iteration counter
     */
    void emit(Signal signal, String vhost, Instant time, long iteration) {
        var source = vhost != null ? LOG_SOURCE_VHOST : LOG_SOURCE_SIMULATOR;
        JSON_LOGGER.write(new SimulationEvent(logSeq++, source, vhost, iteration, time, signal), out);
        out.write('\n');
        simulator.hash(signal.message());
    }

    /**
     * Custom {@code jackson-jr} extension that registers value writers for {@link Signal} (polymorphic
     * dispatch on subtype, emitting {@code type}/{@code message}/subtype fields) and {@link Instant}
     * (ISO-8601 string). The {@link Signal} writer is selected via {@code Signal.class.isAssignableFrom}
     * so that all 14 sealed subtypes are dispatched to the same writer.
     */
    private static final class SignalCodec extends JacksonJrExtension {
        @Override
        protected void register(ExtensionContext ctxt) {
            ctxt.appendProvider(new ReaderWriterProvider() {
                @Override
                public ValueWriter findValueWriter(JSONWriter writeContext, Class<?> type) {
                    if (Signal.class.isAssignableFrom(type)) {
                        return SIGNAL_WRITER;
                    } else if (Instant.class.isAssignableFrom(type)) {
                        return INSTANT_WRITER;
                    } else if (Enum.class.isAssignableFrom(type)) {
                        return ENUM_WRITER;
                    }
                    return null;
                }
            });
        }
    }

    private static final ValueWriter INSTANT_WRITER = new ValueWriter() {
        @Override
        public void writeValue(JSONWriter context, JsonGenerator g, Object value) {
            g.writeString(value.toString());
        }

        @Override
        public Class<?> valueType() {
            return Instant.class;
        }
    };

    /**
     * Serializes any {@link Enum} via {@link Object#toString()} rather than {@link Enum#name()},
     * so that enums overriding {@code toString()} (e.g. {@link com.pingidentity.opendst.common.AssertType})
     * emit their domain-specific wire value.
     */
    private static final ValueWriter ENUM_WRITER = new ValueWriter() {
        @Override
        public void writeValue(JSONWriter context, JsonGenerator g, Object value) {
            g.writeString(value.toString());
        }

        @Override
        public Class<?> valueType() {
            return Enum.class;
        }
    };

    private static final ValueWriter SIGNAL_WRITER = new ValueWriter() {
        @Override
        public void writeValue(JSONWriter context, JsonGenerator g, Object value) {
            var signal = (Signal) value;
            g.writeStartObject();
            // type and message are written explicitly because they are interface methods
            // (or sometimes overrides of interface methods), not record components, so the
            // reflective walk below would not pick them up consistently across subtypes.
            g.writeStringProperty("type", signal.type());
            g.writeStringProperty("message", signal.message());
            try {
                for (var rc : signal.getClass().getRecordComponents()) {
                    if (HANDLED_FIELDS.contains(rc.getName())) {
                        continue;
                    }
                    var fieldValue = rc.getAccessor().invoke(signal);
                    if (fieldValue != null) {
                        g.writePOJOProperty(rc.getName(), fieldValue);
                    }
                }
            } catch (ReflectiveOperationException e) {
                throw new SimulationError("Failed to serialize signal " + signal.getClass(), e);
            }
            g.writeEndObject();
        }

        @Override
        public Class<?> valueType() {
            return Signal.class;
        }
    };

    /** Record component names already emitted by the SIGNAL_WRITER preamble. */
    private static final Set<String> HANDLED_FIELDS = Set.of("type", "message");

    // ── Inner classes ─────────────────────────────────────────────────────────

    /**
     * An {@link OutputStream} assigned as a virtual host's {@code System.out}. Buffers bytes, splits on line
     * separators, and emits each complete line as a {@link ConsoleSignal} (embedding raw JSON if the line is
     * already a JSON object). Every line is hashed into the deterministic state and buffered in
     * {@link #unauditedLogs} for deferred {@link TraceAuditor} processing via {@link #flush()}.
     */
    final class LogWriter extends OutputStream {
        private final Node node;
        private final ByteArrayOutputStream consoleOut = new ByteArrayOutputStream();

        LogWriter(Node node) {
            this.node = node;
        }

        @Override
        public void write(int b) {
            consoleOut.write(b);
        }

        @Override
        public void write(byte[] b, int off, int len) {
            consoleOut.write(b, off, len);
        }

        @Override
        public void flush() {
            if (consoleOut.size() > 0) {
                var str = consoleOut.toString(UTF_8);
                int end = str.indexOf(lineSeparator());
                int start = 0;
                while (end != -1) {
                    log(str.substring(start, end));
                    start = end + lineSeparator().length();
                    end = str.indexOf(lineSeparator(), start);
                }

                try {
                    consoleOut.reset();
                    if (start < str.length()) {
                        consoleOut.write(str.substring(start).getBytes(UTF_8));
                    }
                } catch (IOException e) {
                    // Should never happen
                    throw new SimulationError(e);
                }
            }
        }

        private void log(String message) {
            // Lines that are already structured JSON are embedded raw inside the envelope, bypassing the
            // ConsoleSignal type — useful for nested signals from agents that already speak the protocol.
            // This is a hand-written carve-out: the polymorphic Signal writer registered in JSON_LOGGER
            // cannot embed a raw JSON string, so we write the SimulationEvent envelope manually here.
            if (message != null && message.startsWith("{") && message.endsWith("}")) {
                try (var gen = JSON_LOGGER.createGenerator(out)) {
                    gen.writeStartObject()
                            .writeNumberProperty("lid", logSeq++)
                            .writeStringProperty("source", LOG_SOURCE_VHOST)
                            .writeStringProperty("vhost", node.hostName())
                            .writeNumberProperty("it", simulator.iteration())
                            .writeStringProperty("at", simulator.instant().toString())
                            .writeName("signal");
                    gen.writeRawValue(message);
                    gen.writeEndObject();
                }
                out.write('\n');
                simulator.hash(message);
            } else {
                node.log(new ConsoleSignal(message));
            }
            unauditedLogs.add(new Log(node.hostName(), simulator.instant(), simulator.iteration(), message));
        }
    }

    /**
     * A {@link PrintStream} that close-shields its delegate. Used so that the agent never closes
     * the child JVM's real {@code System.out} (which would prevent any further structured output).
     */
    private static final class CloseShieldPrintStream extends PrintStream {
        CloseShieldPrintStream(PrintStream delegate) {
            super(delegate);
        }

        @Override
        public void close() {
            // Do *not* close
        }
    }
}
