services:
  server:
    class: com.pingidentity.opendst.testapp.SecretSequenceApp$Server
    dir: target/apps/opendst-testapp
    ip: 10.0.0.2
    args: ["8080"]
  client:
    class: com.pingidentity.opendst.testapp.SecretSequenceApp$Client
    dir: target/apps/opendst-testapp
    ip: 10.0.0.3
    args: ["10.0.0.2", "8080"]

traceAuditor:
  class: com.pingidentity.opendst.testapp.SecretSequenceTraceAuditor
  dir: target/apps/opendst-testapp
